version: '3.9'

services:
  bot_services:
    build: .
    container_name: factor_books_bot
    env_file: .env

  redis_service:
    image: redis:alpine
    volumes:
      - redis_db:/data

volumes:
  redis_db: { }